#!/usr/bin/env python3

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from itertools import compress

import matplotlib as mpl
mpl.rc('font',family='Arial')

# load MODIS burned area data
bas = np.load('baf_sums.npy')

